app.config:
  indicator-poll-interval: PT20S
  #  indicator-poll-interval: PT1H
  web-client:
    trace-web-client-requests: false
    ssl-ignore-validation: true
  jwt:
    issuer: http://localhost
    audience: restbox_java
    secret: qweasdzxc123
    time-to-live: PT5H
  users:
    - username: user1
      password: user123
      roles: USER
    - username: user1
      password: user2pwd
      roles: USER
    - username: user3
      password: user3pwd
      roles: USER
    - username: admin
      password: password
      roles: ADMIN,OTHER
  routers:
    testcsr1:
      name: CSR-WAN
      host: 192.168.70.70
      username: rest
      password: restpwd
      type: csrv
    testcsr2:
      name: CSR-AWS
      host: 192.168.70.71
      username: rest2
      password: restpwd2
      type: asr
  boxcontrol:
  - name: b1
    secret: cisco123
    ready: 0
    boxes:
    - type: switch
      id: 0
      status: 0
      descr: red switch
      onfunc: anone
      offfunc: anone
    - type: button
      id: 0
      status: 0
      descr: big red button
      onfunc: anone
      offfunc: anone
    - type: usonic
      id: 0
      status: 0
      descr: ultrasonic sensor
      onfunc: anone
      offfunc: anone
    - type: led
      id: 0
      status: 0
      descr: red light
      rfunc: rfunc1
    - type: led
      id: 1
      status: 0
      descr: green light
      rfunc: rfunc2
  - name: b2
    secret: cisco123
    ready: 0
    boxes:
    - type: switch
      id: 0
      status: 0
      descr: blue switch
      onfunc: anone
      offfunc: anone
    - type: button
      id: 0
      status: 0
      descr: big red button
      onfunc: anone
      offfunc: anone
    - type: usonic
      id: 0
      status: 0
      descr: ultrasonic sensor
      onfunc: anone
      offfunc: anone
    - type: led
      id: 0
      status: 0
      descr: red light
      rfunc: rnone
    - type: led
      id: 1
      status: 0
      descr: green light
      rfunc: rfunc3
