app.config:
  indicator-poll-interval: PT20S
  #  indicator-poll-interval: PT1H
  cisco-rest-api-uri-template: https://{hostname}:55443/api/v1/
  web-client:
    trace-web-client-requests: false
    ssl-ignore-validation: true
  jwt:
    issuer: http://localhost
    audience: restbox_java
    secret: qweasdzxc123
    time-to-live: PT5H
  users:
    - username: user1
      password: user123
      roles: USER
    - username: user1
      password: user2pwd
      roles: USER
    - username: user3
      password: user3pwd
      roles: USER
    - username: admin
      password: password
      roles: ADMIN,OTHER
  routers:
    testcsr1:
      name: CSR-WAN
      host: 192.168.70.70
      username: rest
      password: restpwd
      type: csrv
    testcsr2:
      name: CSR-AWS
      host: 192.168.70.71
      username: rest2
      password: restpwd2
      type: asr
  boxcontrol:
  - name: b1
    secret: cisco123
    boxes:
    - type: switch
      id: 0
      descr: grey switch
      onfunc: anone
      offfunc: anone
    - type: switch
      id: 1
      descr: red switch
      onfunc: afunc1
      offfunc: afunc2
    - type: button
      id: 0
      descr: big red button
      onfunc: afunc3
      offfunc: afunc4
    - type: usonic
      id: 0
      descr: ultrasonic sensor
      onfunc: afunc5
      offfunc: afunc6
    - type: led
      id: 0
      descr: red light
      rfunc: rfunc1
    - type: led
      id: 1
      descr: green light
      rfunc: rfunc2
  - name: b2
    secret: cisco456
    boxes:
    - type: switch
      id: 0
      descr: blue switch
      onfunc: afunc7
      offfunc: afunc8
    - type: button
      id: 0
      descr: big red button
      onfunc: afunc9
      offfunc: afunc10
    - type: usonic
      id: 0
      descr: ultrasonic sensor
      onfunc: afunc11
      offfunc: afunc12
    - type: led
      id: 0
      descr: red light
      rfunc: rfunc3
    - type: led
      id: 1
      descr: green light
      rfunc: rfunc4
# Router functions currently defined in EntityConfiguration:
# READ:
#   rnone   Dummy non-executable read function
#   rfunc1  CSR-WAN Gi3 state is down
#   rfunc2  CSR-WAN Gi3 state is up
#   rfunc3  CSR-AWS Gi1 state is up
#   rfunc4  CSR-AWS Gi1 acl STOPPING enabled
# ACTION:
#   anone   Dummy non-executable action function
#   afunc1  CSR-WAN Gi3 state set to down
#   afunc2  CSR-WAN Gi3 state set to up
#   afunc3  CSR-WAN Gi3 attach input ACL STOP80
#   afunc4  CSR-WAN Gi3 remove input ACL STOP80
#   afunc5  CSR-WAN Gi3 attach input ACL STOP22
#   afunc6  CSR-WAN Gi3 remove input ACL STOP22
#   afunc7  CSR-AWS Gi1 attach input ACL STOP80
#   afunc8  CSR-AWS Gi1 remove input ACL STOP80
#   afunc9  CSR-AWS Gi1 attach input ACL STOPPING
#   afunc10 CSR-AWS Gi1 remove input ACL STOPPING
#   afunc11 CSR-AWS Gi1 attach input ACL STOP443
#   afunc12 CSR-AWS Gi1 remove input ACL STOP443
