app.config:
  jwt:
    audience: restbox_java
    secret: qweasdzxc123
    time-to-live: PT1H
  users:
    - username: user1
      password: user123
      roles: USER
    - username: admin
      password: password
      roles: ADMIN
    - username: user2
      password: test2
      roles: OTHER,ADMIN
  routers:
    testcsr1:
      name: CSR-WAN
      host: 10.1.2.3
      username: rest
      password: restpwd
      type: csrv
    testcsr2:
      name: CSR-WAN2
      host: 10.1.2.4
      username: rest2
      password: restpwd2
      type: asr
